#! /bin/bash
sudo apt update && sudo apt upgrade -y
sudo apt install apache2 libapache2-mod-php php-mysql php-pdo -y
sudo git clone https://github.com/luispfcanales/cloud.git
sudo cp -rf cloud /var/www/html
sudo cp -rf app /var/www/html
echo " #"
echo " # ██╗     ██╗   ██╗██╗███████╗██████╗ ███████╗    ██████╗ ███████╗██╗   ██╗"
echo " # ██║     ██║   ██║██║██╔════╝██╔══██╗██╔════╝    ██╔══██╗██╔════╝██║   ██║"
echo " # ██║     ██║   ██║██║███████╗██████╔╝█████╗      ██║  ██║█████╗  ██║   ██║"
echo " # ██║     ██║   ██║██║╚════██║██╔═══╝ ██╔══╝      ██║  ██║██╔══╝  ╚██╗ ██╔╝"
echo " # ███████╗╚██████╔╝██║███████║██║     ██║         ██████╔╝███████╗ ╚████╔╝"
echo " # ╚══════╝ ╚═════╝ ╚═╝╚══════╝╚═╝     ╚═╝         ╚═════╝ ╚══════╝  ╚═══╝"
echo " # Email: luispfcanales@gmail.com"
echo " # Twitter: @luispfcanales"
echo " # -------------------------------------------------------------------------"
echo " # INGRESE SU IP/app EXAMPLE: (192.168.0.1/app)"
echo " # -------------------------------------------------------------------------"
